const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={tab:'resource',hours:12,stock:[0,0,0],collected:false,strategy:0,levels:[4,6,5,4],assigned:false,stage:0};
const panel=$('#panel'), modal=$('#modal');let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function openModal(content){$('#modal-content').innerHTML=content;modal.showModal()}
function closeModal(){modal.close()}
$('#close-modal').onclick=closeModal;modal.addEventListener('close',()=>{$('#modal-content').innerHTML=''});modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
$('#about').onclick=()=>openModal('<h3>关于这份活动档案</h3><p>本展示根据你提供的「次生预案」活动实录制作，提炼资源采集、营建策略、战备、前哨支点等界面结构。影像与设备画面均取自原视频。</p><p>本页是非官方交互原型。资源产出、策略升级和编组操作为本地演示，不代表游戏实际规则，也不会连接游戏账号。刷新页面将重置演示。原视频中的活动日期为历史记录。</p><div class="modal-meta">SOURCE / 「次生预案」活动.mp4 · 04:33</div>');
$('#play-reference').onclick=()=>openModal('<h3>次生预案 · 活动实录</h3><video controls autoplay playsinline preload="metadata" src="assets/reference.mp4"></video><p>原始参考影像 · 历史活动记录</p>');
function setTab(id,focus=false){state.tab=id;$$('[data-tab]').forEach(b=>{let active=b.dataset.tab===id;b.setAttribute('aria-selected',active);b.tabIndex=active?0:-1;if(active&&focus)b.focus()});panel.setAttribute('aria-labelledby','tab-'+id);renderPanel()}
$$('[data-tab]').forEach(b=>{b.onclick=()=>setTab(b.dataset.tab);b.onkeydown=e=>{let keys=['resource','strategy','armory','outpost'],i=keys.indexOf(state.tab);if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();setTab(keys[e.key==='Home'?0:e.key==='End'?3:(i+(e.key==='ArrowRight'?1:3))%4],true)}}});
$$('[data-go]').forEach(b=>b.onclick=()=>{setTab(b.dataset.go);$('#workbench').scrollIntoView({behavior:'smooth'})});
function resourceValues(){return state.collected?[0,0,0]:[state.hours*120,state.hours*6,state.hours*3]}
function resourceMarkup(){const values=resourceValues();return `<div class="panel-layout"><div><div class="panel-title"><h3>临时仓储</h3><span>STORAGE / 48H MAX</span></div><div class="resource-cards">${['基础资源','营建材料','战备资料'].map((n,i)=>`<div class="resource-card"><span class="resource-symbol">${['◈','⬡','▤'][i]}</span><label>${n} <small> / DEMO</small></label><strong id="value-${i}">${values[i].toLocaleString()}</strong><small>+ ${[120,6,3][i]} / H · 模拟产出</small></div>`).join('')}</div><div class="progress-label"><span>仓储占用</span><span id="storage-label">${state.collected?0:state.hours} / 48 小时</span></div><div class="progress"><i id="storage-bar" style="width:${state.collected?0:state.hours/48*100}%"></i></div><p class="note">影像规则：临时仓储最多容纳 48 小时的资源产出，堆满后需及时转运。</p></div><div class="control-box"><h4>生产效率模拟</h4><p>拖动时间轴预览资源积累，点击转运，将临时仓储中的资源收入演示库存。</p><label for="hours">累计生产时长 <b id="hours-label">${state.hours} 小时</b></label><input id="hours" type="range" min="0" max="48" value="${state.hours}" aria-label="累计生产时长"><button class="primary" id="collect" ${state.collected||!state.hours?'disabled':''}>${state.collected?'已完成转运':'转运入库'} <span>↗</span></button><div class="bank" id="bank">演示库存 / ${state.stock.map(n=>n.toLocaleString()).join(' · ')}</div><button id="reset" class="outline">重置模拟</button></div></div>`}
function renderPanel(){if(state.tab==='resource'){panel.innerHTML=resourceMarkup();$('#hours').oninput=e=>{state.hours=+e.target.value;state.collected=false;resourceValues().forEach((v,i)=>$('#value-'+i).textContent=v.toLocaleString());$('#hours-label').textContent=state.hours+' 小时';$('#storage-label').textContent=state.hours+' / 48 小时';$('#storage-bar').style.width=state.hours/48*100+'%';$('#collect').disabled=!state.hours;$('#collect').innerHTML='转运入库 <span>↗</span>'};$('#collect').onclick=()=>{if(state.collected||!state.hours)return;resourceValues().forEach((v,i)=>state.stock[i]+=v);state.collected=true;renderPanel();$('#collect').focus();toast('转运完成，资源已计入演示库存')};$('#reset').onclick=()=>{state.hours=12;state.stock=[0,0,0];state.collected=false;renderPanel();toast('资源模拟已重置')};}
if(state.tab==='strategy'){const names=['防护策略','远程支援','协同作业','机动部署'];panel.innerHTML=`<div class="panel-layout"><div><div class="panel-title"><h3>营建策略配置</h3><span>CONSTRUCTION STRATEGIES</span></div><div class="strategy-list">${names.map((n,i)=>`<button class="strategy-card" data-strategy="${i}" aria-pressed="${state.strategy===i}"><strong>${['⬡','⌁','⌘','△'][i]}　${n}</strong><span>LV ${state.levels[i]} ${state.levels[i]===6?' / MAX':''}</span><small>演示策略 ${String(i+1).padStart(2,'0')} · 点击查看</small></button>`).join('')}</div></div><div class="control-box"><h4>${names[state.strategy]}</h4><p>参考营建策略界面的多卡片布局与等级状态，体验策略选择及升级反馈。此处策略名称及等级上限为交互示例。</p><label>当前演示等级 <b class="yellow">LV ${state.levels[state.strategy]} / 6</b></label><div class="progress"><i style="width:${state.levels[state.strategy]/6*100}%"></i></div><button id="upgrade" class="primary" ${state.levels[state.strategy]===6?'disabled':''}>${state.levels[state.strategy]===6?'已达演示上限':'升级所选策略'} <span>↑</span></button></div></div>`;$$('[data-strategy]').forEach(b=>b.onclick=()=>{state.strategy=+b.dataset.strategy;renderPanel();$(`[data-strategy="${state.strategy}"]`).focus()});$('#upgrade').onclick=()=>{if(state.levels[state.strategy]<6)state.levels[state.strategy]++;renderPanel();toast('策略已升级至 LV '+state.levels[state.strategy])};}
if(state.tab==='armory'){panel.innerHTML=`<div class="panel-layout"><div><div class="panel-title"><h3>干员任命</h3><span>ARMORY / PERSONNEL</span></div><img class="operator-photo" src="assets/frame-07.jpg" alt="原视频中的干员任命界面"></div><div class="control-box"><h4>战备编组预览</h4><p>通过任命操作切换编组状态。这里使用匿名演示席位，不复刻干员能力与实际战斗数值。</p><div class="slots" aria-label="编组席位">${[0,1,2].map((n)=>`<div class="slot">${state.assigned?['Ⅰ','Ⅱ','Ⅲ'][n]:'+'}</div>`).join('')}</div><div class="bank">${state.assigned?'当前状态 / 3 个演示席位已就绪':'当前状态 / 等待任命'}</div><button class="primary" id="assign">${state.assigned?'撤销演示编组':'一键任命演示编组'} <span>→</span></button></div></div>`;$('#assign').onclick=()=>{state.assigned=!state.assigned;renderPanel();$('#assign').focus();toast(state.assigned?'三个演示席位已就绪':'演示编组已撤销')};}
if(state.tab==='outpost'){const stages=['RM-TR-1','RM-1','RM-5'];panel.innerHTML=`<div class="panel-layout"><div><div class="panel-title"><h3>前哨支点 · 行动地图</h3><span>FRONTIER OUTPOSTS</span></div><div class="route">${stages.map((n,i)=>`<button class="node" data-stage="${i}" aria-pressed="${state.stage===i}">◇<br><br>${n}</button>`).join('')}</div><p class="note">关卡编号取自实录。节点连接及选中状态仅用于展示浏览流程。</p></div><div class="control-box"><h4>${stages[state.stage]} <span class="yellow">/ 已选中</span></h4><p>从行动地图选择关卡，预览视频中的作战场景。此页面不包含真实战斗模拟。</p><label>预览内容 <b>作战实录截图</b></label><button class="primary" id="stage-preview">查看作战场景 <span>↗</span></button></div></div>`;$$('[data-stage]').forEach(b=>b.onclick=()=>{state.stage=+b.dataset.stage;renderPanel();$(`[data-stage="${state.stage}"]`).focus()});$('#stage-preview').onclick=()=>openModal('<h3>作战场景 · 影像预览</h3><img src="assets/frame-11.jpg" alt="活动实录中的战斗画面"><p>原视频 04:17 处的作战截图，作为行动预览；不声称对应所选关卡。</p>');}}
const records=[{image:'01',title:'资源采集 · 生产网络',en:'RESOURCE GATHERING',time:'00:29',category:'system',description:'多种资源通过连线汇入生产设备，底部提示临时仓储的容量上限。'},{image:'03',title:'营建策略 · 等级配置',en:'CONSTRUCTION STRATEGIES',time:'01:15',category:'system',description:'策略以多列卡片呈现，包含等级、图标和说明，荧光黄突出关键等级信息。'},{image:'11',title:'前哨支点 · 作战现场',en:'FRONTIER OUTPOSTS',time:'04:17',category:'battle',description:'影像中的实际作战场景，展示网格战场、干员部署与状态信息。'}];
function gallery(filter='all'){$('#gallery').innerHTML=records.filter(r=>filter==='all'||r.category===filter).map(r=>`<button class="gallery-card" data-record="${r.image}"><div class="gallery-image"><img src="assets/frame-${r.image}.jpg" alt="${r.title}" loading="lazy"><span>${r.time} ↗</span></div><div class="gallery-info"><span><strong>${r.title}</strong><small>${r.en}</small></span><b>↗</b></div></button>`).join('');$$('[data-record]').forEach(b=>b.onclick=()=>{const r=records.find(x=>x.image===b.dataset.record);openModal(`<h3>${r.title}</h3><img src="assets/frame-${r.image}.jpg" alt="${r.title}"><p>${r.description}</p><div class="modal-meta">SOURCE VIDEO / ${r.time}</div>`)})}
$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});gallery(b.dataset.filter)});
const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)$$('.topbar nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+e.target.id))})},{rootMargin:'-15% 0px -60% 0px'});$$('main>section').forEach(s=>observer.observe(s));renderPanel();gallery();
